/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_appsync_graphqlEndpoint": "https://yyykb3jz2nhbbndtybqis3j5ly.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-oxlg5zxhqfhbfkvulnm7cfysp4",
    "aws_cognito_identity_pool_id": "eu-central-1:5148d9fa-6561-46ba-b7e0-06ffe5e6e75c",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_hRCcEpZm9",
    "aws_user_pools_web_client_id": "6is1ut1fm3fc1nn98fr59ofmp",
    "oauth": {}
};


export default awsmobile;
